### ISSUE TITLE
torch._inductor.exc.InductorError: RuntimeError: CUDA driver error: file not found

### ISSUE THREAD

**Issue by zraul** [woct0rdho/triton-windows#167]
### Describe the bug

!!! Exception during processing !!! RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\execution.py", line 499, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 316, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 290, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "F:\ComfyUI\ComfyUI\execution.py", line 278, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_sampler.py", line 3048, in process
    raise e
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_sampler.py", line 2933, in process
    noise_pred, noise_pred_ovi, self.cache_state = predict_with_cfg(
                                                   ^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_sampler.py", line 1543, in predict_with_cfg
    raise e
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes_sampler.py", line 1414, in predict_with_cfg
    noise_pred_cond, noise_pred_ovi, cache_state_cond = transformer(
                                                        ^^^^^^^^^^^^
  File "F:\ComfyUI\python\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\modules\model.py", line 2850, in forward
    x, x_ip, lynx_ref_feature, x_ovi = block(x, x_ip=x_ip, lynx_ref_feature=lynx_ref_feature, x_ovi=x_ovi, **kwargs) #run block
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python\Lib\site-packages\torch\_dynamo\eval_frame.py", line 375, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python\Lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python\Lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python\Lib\site-packages\torch\_dynamo\eval_frame.py", line 749, in compile_wrapper
    raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python\Lib\site-packages\torch\_inductor\compile_fx.py", line 923, in _compile_fx_inner
    raise InductorError(e, currentframe()).with_traceback(
  File "F:\ComfyUI\python\Lib\site-packages\torch\_inductor\compile_fx.py", line 907, in _compile_fx_inner
    mb_compiled_graph = fx_codegen_and_compile(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python\Lib\site-packages\torch\_inductor\compile_fx.py", line 1578, in fx_codegen_and_compile
    return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python\Lib\site-packages\torch\_inductor\compile_fx.py", line 1456, in codegen_and_compile
    compiled_module = graph.compile_to_module()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python\Lib\site-packages\torch\_inductor\graph.py", line 2293, in compile_to_module
    return self._compile_to_module()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python\Lib\site-packages\torch\_inductor\graph.py", line 2303, in _compile_to_module
    mod = self._compile_to_module_lines(wrapper_code)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python\Lib\site-packages\torch\_inductor\graph.py", line 2371, in _compile_to_module_lines
    mod = PyCodeCache.load_by_key_path(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python\Lib\site-packages\torch\_inductor\codecache.py", line 3296, in load_by_key_path
    mod = _reload_python_module(key, path, set_sys_modules=in_toplevel)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python\Lib\site-packages\torch\_inductor\runtime\compile_tasks.py", line 31, in _reload_python_module
    exec(code, mod.__dict__, mod.__dict__)
  File "C:\Users\卡卡\AppData\Local\Temp\torchinductor_卡卡\iq\ciqjk3fkpcy67uo7lhvaic36yfyrj22m2uqn3k72bjdl2mfmidft.py", line 42, in <module>
  File "F:\ComfyUI\python\Lib\site-packages\torch\_inductor\async_compile.py", line 404, in triton
    kernel.precompile(
  File "F:\ComfyUI\python\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 411, in precompile
    self._make_launchers()
  File "F:\ComfyUI\python\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 568, in _make_launchers
    launchers.append(result.make_launcher())
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 1415, in make_launcher
    self.kernel.load_kernel(device)
  File "F:\ComfyUI\python\Lib\site-packages\torch\_inductor\runtime\static_cuda_launcher.py", line 113, in load_kernel
    (self.function, self.n_regs, self.n_spills) = _StaticCudaLauncher._load_kernel(
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch._inductor.exc.InductorError: RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

### Environment details

GPU:3090
Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
pytorch version: 2.8.0+cu128
xformers version: 0.0.32.post2
triton-windows: 3.4.0.post21

**Comment by zraul** [comment]
> Before running ComfyUI, did you run the test script [here](https://github.com/woct0rdho/triton-windows#test-if-it-works)?
> 
> Did you clear the caches [here](https://github.com/woct0rdho/triton-windows#importerror-dll-load-failed-while-importing-cuda_utils)?

I run the test_trion.py and the output is as follows:
```
tensor([0., 0., 0.], device='cuda:0')
If you see tensor([0., 0., 0.], device='cuda:0'), then it works
```

Then i clean the cache file
```
C:\Users\<your username>\.triton\cache\
C:\Users\<your username>\AppData\Local\Temp\torchinductor_<your username>\
```
and try reinstall the package by command pip install -U "triton-windows<3.5", the output is as follows:
```
WARNING: Ignoring invalid distribution ~lash-attn (F:\ComfyUI\python\Lib\site-packages)
Collecting triton-windows<3.5
  Using cached triton_windows-3.4.0.post21-cp311-cp311-win_amd64.whl.metadata (1.8 kB)
Requirement already satisfied: setuptools>=40.8.0 in f:\comfyui\python\lib\site-packages (from triton-windows<3.5) (65.0.0)
Using cached triton_windows-3.4.0.post21-cp311-cp311-win_amd64.whl (42.7 MB)
WARNING: Ignoring invalid distribution ~lash-attn (F:\ComfyUI\python\Lib\site-packages)
Installing collected packages: triton-windows
WARNING: Ignoring invalid distribution ~lash-attn (F:\ComfyUI\python\Lib\site-packages)
Successfully installed triton-windows-3.4.0.post21
```

Same error again
